### PR TITLE
dev-lang/php

### PR DESCRIPTION
**Pull request by org-tekeli-borisp**
Summary
========
* switched to autogen.yaml
* deleted multiple obsolete templates and patch files

Test Plan
========
* Doit
```
doit
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Download from https://github.com/php/php-src/tarball/0454901ed1518cfb42bc77ac91728591b58c3e6e verified as valid tar.gz archive.                                                                                   
INFO     Created: php-8.4.1.ebuild 
```
* Make it available in a own repo tree or by seeding into a local overlay
* Emerge it
```
workstation-mark-repo ~ # emerge -av php

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] dev-lang/php-8.4.1:8.4::overlay  USE="acl argon2 berkdb bzip2 cgi cli ctype curl exif fileinfo filter flatfile fpm gd gdbm iconv intl ipv6 mysql mysqli nls opcache pcntl pdo phar posix readline session simplexml sockets sodium spell sqlite ssl tidy tokenizer truetype unicode webp xml xmlreader xmlwriter xslt zip zlib -apache2 -apparmor -bcmath -calendar -cdb -cjk -coverage -debug -embed -enchant -ffi -firebird -ftp -gmp -imap -inifile -iodbc -kerberos -ldap -ldap-sasl -libedit -libressl -lmdb -mhash -mssql -oci8-instant-client -odbc -phpdbg -postgres -qdbm (-selinux) -session-mm -sharedmem -snmp -soap -sysvipc -test -threads -tokyocabinet -xpm -zts" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-lang/php-8.4.1::overlay
>>> Installing (1 of 1) dev-lang/php-8.4.1::overlay
>>> Recording dev-lang/php in "world" favorites file...
>>> Jobs: 1 of 1 complete                           Load avg: 5.00, 7.52, 5.73

 * Messages for package dev-lang/php-8.4.1:

 * Installing php.ini for cli into /etc/php/cli-php8.4
 * 
 * Adding opcache to /etc/php/cli-php8.4/ext
 * Installing php.ini for cgi into /etc/php/cgi-php8.4
 * 
 * Adding opcache to /etc/php/cgi-php8.4/ext
 * Installing php.ini for fpm into /etc/php/fpm-php8.4
 * 
 * Adding opcache to /etc/php/fpm-php8.4/ext
 * To build extensions for this version of PHP, you will need to
 * add php8-4 to your PHP_TARGETS USE_EXPAND variable.
 * 
 * For details on how version slotting works, please see
 * the wiki:
 * 
 *   https://wiki.gentoo.org/wiki/PHP
 * 
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
workstation-mark-repo ~ # 

```
* Running it
```
workstation-mark-repo ~ # php -version
PHP 8.4.1 (cli) (built: Nov 24 2024 15:41:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
workstation-mark-repo ~ # 

```

### CODE REVIEW

**Comment by org-tekeli-borisp** [comment]
@geaaru  added multiple PHP versions to autogen.yam

```
doit
INFO     Cloning/updating kit-fixups to access generators (--fast to use as-is)                                                                                                                                            
INFO     executing: (cd /home/borisp/repo_tmp/source-trees/kit-fixups && git pull --ff-only)                                                                                                                               
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Autogen: dev-lang/php-8.3.14                                                                                                                                                                                      
INFO     Autogen: dev-lang/php-8.2.26                                                                                                                                                                                      
INFO     Autogen: dev-lang/php-8.1.31                                                                                                                                                                                      
INFO     Download from https://github.com/php/php-src/tarball/a3695d49e878eb2ebbf4645a0975cb5e225fbc7d verified as valid tar.gz archive.                                                                                   
INFO     Created: php/php-8.2.26.ebuild                                                                                                                                                                                    
INFO     Download from https://github.com/php/php-src/tarball/0454901ed1518cfb42bc77ac91728591b58c3e6e verified as valid tar.gz archive.                                                                                   
INFO     Created: php/php-8.4.1.ebuild                                                                                                                                                                                     
INFO     Download from https://github.com/php/php-src/tarball/38123aca18c3c1bd1f109ec77af2f175d7afcf35 verified as valid tar.gz archive.                                                                                   
INFO     Created: php/php-8.1.31.ebuild                                                                                                                                                                                    
INFO     Download from https://github.com/php/php-src/tarball/dc83dee9003edfff53f0f7d057bf79650c7f10dc verified as valid tar.gz archive.                                                                                   
INFO     Created: php/php-8.3.14.ebuild   
```

**Comment by geaaru** [comment]
1) I see that the patch `php-iodbc-header-location.patch` is no more applied to slot 8.1 and 8.2. Is this correct?

2) The migration to autogen.yaml fixes issues with PHP.net website but lose the automatic updated of branch 8.1, 8.2 and 8.3. I don't know if exists a way to have multiple selector for every minor release in order to automatically get new versions with YAML. I dunno if could be better update autogen.py in order to use github api (from github-1) generator and retrieve all minor releases automatically.

FYI: if you need update the commit you can rebase it and force a push in order to have only one commit in this PR.
Example:
```
$> git commit -m "Add change n2" .
$> git log -n3 .
$> git rebase -i <hash-log3>
```

**Comment by org-tekeli-borisp** [comment]
@geaaru  `php-iodbc-header-location.patch` still a thing but only if your activate `apache` use flag ;) This was a bug in the old templates.
image

**Comment by org-tekeli-borisp** [comment]
@geaaru  what do you think about the the updated yaml solution?

**Comment by org-tekeli-borisp** [comment]
```
doit
INFO     Cloning/updating kit-fixups to access generators (--fast to use as-is)                                                                                                                                            
INFO     executing: (cd /home/borisp/repo_tmp/source-trees/kit-fixups && git pull --ff-only)                                                                                                                               
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Autogen: dev-lang/php (latest)                                                                                                                                                                                    
INFO     Created: php-8.2.26.ebuild                                                                                                                                                                                        
INFO     Created: php-8.4.1.ebuild                                                                                                                                                                                         
INFO     Created: php-8.1.31.ebuild                                                                                                                                                                                        
INFO     Created: php-8.3.14.ebuild
```

**Review by geaaru — APPROVED** [review]

**Pull request merged**
