### PR TITLE
Cleanup python 2.7 compat ebuilds

### PR DESCRIPTION
**Pull request by geaaru**
Closes: macaroni-os/mark-issues#71

:boom: a big change... to test with attention in `mark-testing` branch.

### CODE REVIEW

**Comment by org-tekeli-borisp** [comment]
@geaaru  How one could test this one?  Probably the best way were to build stages (stages3, gnome etc.) with the mark-testing tree? In a some kind of CI pipeline?

**Comment by geaaru** [comment]
Yeah, it's something related to `mark-devkit` that we need to complete. I will prepare an experimental *job* for `mark-testing` branch soon.

**Comment by org-tekeli-borisp** [comment]
After merging
```
INFO     executing: cd                                                          
         /home/tree/mark-testing/repo_tmp/dest-trees/python-modules-kit && git  
         add 'metadata' 'LICENSE.txt' 'dev-python' 'profiles' 'virtual'         
INFO     Running step Autogen for                                               
         /home/tree/mark-testing/repo_tmp/dest-trees/python-modules-kit         
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/doit", line 102, in <module>
    success = asyncio.run(main_thread())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/lib/python-exec/python3.9/doit", line 93, in main_thread
    result = await pkgtools.autogen.start()
  File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py", line 653, in start
    queue_all_yaml_autogens(yaml_autogens)
  File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py", line 552, in queue_all_yaml_autogens
    for rule_name, rule in safe_load(myf.read()).items():
  File "/usr/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3.9/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.9/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/usr/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.9/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 2467, column 22:
            python_compat: python3+
                         ^
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/python-modules
         -kit/curated && doit --fast --release mark --fastpull_scope=local      
         --moonbeam --prod                                                      
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups -- offset     
         python-modules-kit/curated.                                            
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 422,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 89,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups -- offset     
         python-modules-kit/curated.                                            
WARNING  The following kits had metadata extraction errors:                     
WARNING  * core-kit branch mark-testing   -- 2 errors.                          
WARNING  The following kits had metadata extraction errors:                     
WARNING  * media-kit branch mark-testing  -- 3 errors.                          
WARNING  metadata extraction errors errors logged to                            
         /home/tree/mark-testing/repo_tmp/tmp.                                  
[?25h
```

**Comment by org-tekeli-borisp** [comment]
the tree regeneration problem should be solved with https://github.com/macaroni-os/kit-fixups/pull/104

**Pull request merged**
